spyrmsd/rmsd.py
spyrmsd/spyrmsd.py
tests/molecules.py
tests/test_pyrmsd.py
tests/test_rmsd.py

Add `multirmsd_isomorphic` function to cache the graph isomorphism. Caching can be turned off with the `cache=False` argument.
Caching makes `spyrmsd` much faster in most cases (`28.25` ms on average with cache versus ` 143.24` ms on average without cache, for the first 75 systems) but it's still an order of magnitude slower than `obrms` (`6.74` ms on average).
Solves #11.

Cache Graph Isomorphism

---

spyrmsd/molecule.py

Fix #17 by invalidating the molecular graph (`self.G = None`) after stripping hydrogen atoms. This prevents possible divergence between the molecular graph and the adjacency matrix.

Reset Graph when Stripping

---

spyrmsd/io.py

Make OpenBabel and RDKit completely optional, so that `spyrmsd` can be used as a standalone library.

Make OpenBabel and RDKit Optional

---

docs/source/tutorials/tutorial.ipynb
docs/source/tutorials/tutorial.rst
spyrmsd/graphs/gt.py
spyrmsd/graphs/nx.py
spyrmsd/io.py
spyrmsd/optional/obabel.py
spyrmsd/spyrmsd.py
tests/data/molecules/1a99_ligand.pdb
tests/test_io.py

Load molecules directly into a `spyrmsd.molecule.Molecule` object and fix problem with single-model PDB file when loaded with `spyrmsd.io.loadall`/`spyrmsd.io.loadallmols`.

Load Molecules Into Molecule Object

---

spyrmsd/spyrmsd.py

Print an error message and exit with code `-1` when a file is not found instead of throwing an exception and printing the whole traceback.

Error Message when File Not Found

---

.github/workflows/mypy.yml
spyrmsd/hungarian.py
spyrmsd/molecule.py
spyrmsd/optional/obabel.py
spyrmsd/optional/rdkit.py
spyrmsd/utils.py
tests/test_graph.py
tests/test_molecule.py

Fix #41; it is now possible to build a `spyrmsd.molecule.Molecule` directly from an OpenBabel or RDKit molecules.
This PR also solves a unreported problem where `to_molecule` would fail with `adjacency=False` (which was not tested).
Some changes are introduced for compatibility with the latest version of `mypy`.

OpenBabel and RDKit constructors

---

spyrmsd/optional/obabel.py
spyrmsd/optional/rdkit.py
spyrmsd/spyrmsd.py
tests/test_spyrmsd.py

Allow wrapper to deal with single molecule as input, instead of supporting only a list of molecules. Fix #48.

Allow RMSD wrapper to deal with single molecule

---

.pre-commit-config.yaml
CHANGELOG.md
README.md

Add [pre-commit](https://pre-commit.com/) configuration file. This allows to install pre-commit `git` hooks (`pre-commit install`) so that every commit runs the same checks as CI (`black`, `flake8`, `isort`, `mypy`).

Add pre-commit configuration file

---

CHANGELOG.md
spyrmsd/graphs/gt.py
spyrmsd/graphs/nx.py
tests/test_graph.py
tests/test_rmsd.py

Fix #61 by explicitly defining the number of vertices when creating a `graph-tool` graph from an adjacency matrix.
This PR also add a warning for disconnected graphs, but might slowing down things for something that is not really useful in standard cases (i.e. small molecules).

Fix number of nodes in graph-tool graphs with disconnected single nodes

---

CHANGELOG.md
README.md
spyrmsd/graph.py
spyrmsd/graphs/_common.py
spyrmsd/graphs/gt.py
spyrmsd/graphs/nx.py
spyrmsd/hungarian.py
spyrmsd/rmsd.py
tests/test_graph.py
tests/test_molecule.py

Fix #63. Add support for more types as node properties (including strings) with `graph-tool`. This allows to perform node matching using not only atomic numbers but also elements, atom types, ..., which is already the case for `networkx`.
TODO:

Expand node attribute types for graph-tool

---

CHANGELOG.md
spyrmsd/exceptions.py
spyrmsd/graphs/gt.py
spyrmsd/graphs/nx.py
tests/test_graph.py

Add exception specifically for graph isomorphism. It is derived from the previous exception `ValueError`, therefore it should not affect downstream usage.

Add exception specifically for graph isomorphism

---

.github/workflows/pypi.yml
README.md

This PR is an attempt to fix issue #54 . The same error described in #54 was obtained locally with `flit==3.0.0`, which is a version that used to work. The `unknown+0` version was picked up at first, after fetching the new tag from the repository. However, installing `spyrmsd` with
```bash
pip install -e .
``` 
seemed to fix the issue.
This PR adds installation of `spyrmsd` before `flit build`, which hopefully will allow `flit` to pick up the correct version from the tag.

Try to install package before deployment

---

CHANGELOG.md
README.md
spyrmsd/__main__.py

When using `spyrmsd` as a standalone tool, RDKit or OpenBabel need to be manually installed, since they are optional dependencies (if `spyrmsd` is used as a library).
This PR adds an error message if neither OpenBabel nor RDKit can be imported. Close #79 and close #80.

Better error message when RDKit or OpenBabel are not installed

---

.coveragerc
CHANGELOG.md
README.md
docs/source/installation.rst
setup.py
spyrmsd/optional/obabel.py

* Remove outdated information about RDKit from the documentation
* Add `rdkit` and `openbabel` as `extra_requires`
* Remove support Open Babel 2
Close #82, close #83.

RDKit and OpenBabel cleanup

---

CHANGELOG.md
spyrmsd/optional/rdkit.py

Some code paths lead to `NotImplementedError` exceptions. The exception are sometimes unclear an surprising to users (see #88). Close #89.
This PR adds proper error messages, to clarify the problem.

Add details on NotImplementedError exceptions

---

CHANGELOG.md
tests/conftest.py
tests/test_benchmarks.py
tests/test_graph.py

Fix #100. Additionally, takes care of the following `pytest` warning:
```
/Users/romeli/mambaforge/envs/spyrmsd/lib/python3.11/site-packages/_pytest/mark/structures.py:357: PytestRemovedIn9Warning: Marks applied to fixtures have no effect
See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
store_mark(func, self.mark)
```

Fix tests for pytest 8

---

CHANGELOG.md
pyproject.toml

Hi, I'm opening this pull request as part of a push to modernise how packages use [Flit](https://flit.pypa.io/en/stable/) as a Python build backend.
Using `flit_core` as the backend in place of `flit` is [recommended in the docs](https://flit.pypa.io/en/stable/pyproject_toml.html#build-system-section), and will make it faster for tools like pip & [build](https://build.pypa.io/en/latest/) to build your package from source, as it has fewer dependencies to install.
Specifying an explicit version range (`>=2,<4`) helps to ensure that your package can still be readily built from source despite changes in future major versions of Flit, because it will still use version 3.x. For instance, a future version is likely to drop support for the `[tool.flit.metadata]` table, in favour of the …

Update build system to flit_core

---

.github/workflows/pytest.yml
.pre-commit-config.yaml
CHANGELOG.md
CITATION.cff
devtools/conda-envs/spyrmsd-test-rdkit-all.yaml
spyrmsd/__init__.py
spyrmsd/graph.py
spyrmsd/molecule.py
tests/test_graph.py
tests/test_molecule.py

Hi,
Here is my second try at implementing the backend selection feature. I've been quite busy, so that's why it took a bit longer than I wanted to put this pull request. Either way, below is a short summary:
I only modified graph.py, and I tried to change as little as possible.
I use environment variables to check and update backend. I also added a function to check all available backends, and to see the current backend. (That last one maybe is a bit redundant and could be removed). 
Everything seems to work fine, except there is one edge-case/"bug" with the to_graph() functionality of a molecule: if you use this before and after switching to another backend for the same molecule, it will still return the graph of the old backend because of the cache. I would propose to make use of a …

Add functionality to select backend

---

CHANGELOG.md
README.md
docs/source/tutorials/tutorial.ipynb
docs/source/tutorials/tutorial.rst
spyrmsd/__main__.py
spyrmsd/graph.py
tests/test_graph.py
tests/test_molecule.py

Close #108 and close #109.
This PR adds documentation related to #107:
* Add doc to `README`
* Add doc to tutorial (website)
* Add docstrings to functions (unfortunately they don't appear in the API documentation since they are private)
This PR adds the `-g/--graph-backend` to manually select a backend from CLI.
Additionally, the following cleanup is done:
* Use `importlib.utils` to check if a package is available, without importing it
* Re-work how internal alias dictionaries are constructed
* Make backend test more general, in preparation to #111

Documentation and CLI for backend selection

---

CHANGELOG.md
tests/test_benchmarks.py
tests/test_graph.py
tests/test_io.py
tests/test_large.py
tests/test_molecule.py
tests/test_qcp.py
tests/test_rmsd.py
tests/test_utils.py

Some test names are not very descriptive, and can create confusion (see  https://github.com/RMeli/spyrmsd/pull/113#issuecomment-2002642711). This PR introduces IDs in tests in order to have better and more explicit test names (when running with `--verbose`, as in CI).
Close #115.

Use IDs in tests

---

.github/workflows/flake8.yml
.github/workflows/mypy.yml
.github/workflows/pypi.yml
.github/workflows/pytest.yml
.pre-commit-config.yaml
CHANGELOG.md

Update GitHub actions. Avoids the following warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, codecov/codecov-action@v3.

Update GitHub actions and pre-commit configuration

---

CHANGELOG.md
README.md
devtools/conda-envs/spyrmsd-all.yaml
devtools/conda-envs/spyrmsd-docs.yaml
devtools/conda-envs/spyrmsd.yaml
docs/source/installation.rst
pyproject.toml
setup.py
spyrmsd/__main__.py
spyrmsd/graph.py

Close https://github.com/RMeli/spyrmsd/issues/121.
* Make `rustworkx` the default backend when installing with `pip`
* The same change will be reflected in the condo-forge recipe
* Change the order of precedence for the default backend: `networkx` is the very last resort

Make rustworkx the default backend in pip

---

CHANGELOG.md
setup.py
spyrmsd/__init__.py
spyrmsd/__main__.py

* Add `--version` to CLI
* Fix #126 
* Fix program name
* Update development version to `0.9.0-dev`

Add --version command to CLI and add -dev to develop version

---

.pre-commit-config.yaml
devtools/conda-envs/spyrmsd-test-rdkit-nogt.yaml

Remove RDKit pin introduced in #134. Closes #135.
https://github.com/conda-forge/rdkit-feedstock/pull/169

Remove RDKit pin

---

.github/workflows/pytest.yml

CI started failing with the following error:
> Warning: Future Miniforge releases will NOT build Mambaforge installers. We advise you switch to Miniforge at your earliest convenience. More details at [https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/.](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/)
Warning: ERROR: executing pre_install.sh failed
Reason:
> October 2024: The Mambaforge installers will refuse to install during several pre-specified date ranges (i.e., ["brownouts"](https://en.wikipedia.org/wiki/Brownout_(software_engineering))) in order to encourage users to switch to Miniforge.
This PR switches from mambaforge to the latest miniforge release.

Use miniforge instead of mambaforge

---

CHANGELOG.md
spyrmsd/rmsd.py
tests/test_rmsd.py

I found it useful to obtain the atom mapping corresponding to the lowest RMSD. This is something that RDKit's `CalcRMS` function lacks. For that I added a new function, rather than modifying `symmrmsd`, to avoid conflicts with existing implementations.
- Added function `symmrmsd_and_isomorphism `, which is identical to `symmrmsd` but also returns the best isomorphism for each minimum RMSD
- Modified `_rmsd_isomorphic_core` to return the best isomorphism
- Adapted return value of `_rmsd_isomorphic_core` for function `symmrmsd`
- Changed type hints for function `symmrmsd`

Optionally return best graph isomorphism
